set(F4SE_RUNTIME_VERSION_REGEX "^#define CURRENT_RELEASE_RUNTIME[ \t]+RUNTIME_VERSION_(([0-9]+)_([0-9]+)_([0-9]+)(_([0-9]+))?)()()[ \t]*(/.*)?$")

file(STRINGS f4se/f4se_common/f4se_version.h F4SE_VERSION_LINE REGEX "${F4SE_RUNTIME_VERSION_REGEX}")
string(REGEX REPLACE "${F4SE_RUNTIME_VERSION_REGEX}" "\\1" F4SE_VERSION_TAG "${F4SE_VERSION_LINE}")
string(REPLACE "_" "." F4SE_VERSION_STR ${F4SE_VERSION_TAG})
